name: Tests

on:
  push:
    branches:
      - main
      - tests
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup EdgeDB
        uses: edgedb/setup-edgedb@v1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest -v
