name: Tests

on:
  push:
    branches:
      - main
      - tests
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install EdgeDB
        uses: edgedb/setup-edgedb@v1

      - name: Setup Edgedb
        run: |
          edgedb project init --non-interactive
